/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tetris;


import java.awt.Graphics;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author diana
 */
public class Main extends javax.swing.JFrame {

    public int score;
    public int highscore;
    public int[][] field;
    public String piecetypes = "OLJITSZ";
    public Color[] colors = {Color.BLACK, Color.RED, Color.ORANGE, Color.YELLOW, Color.PINK, Color.GREEN, Color.BLUE, Color.MAGENTA};
    public int scale = 60;
    public int[] testpos = new int[]{4, -1};
    
    public Field testfield = new Field(10, 17);
    
    public Tetromino mytest = new Tetromino("T", testpos, scale);
    
    public Timer clock = new Timer(100, new ActionListener() {
        
        public void actionPerformed(ActionEvent e) {
            tick();
            playfield.repaint();
        }
    });
    
    public class MyPanel extends JPanel {
        @Override
        public void paint(Graphics g) {
            super.paint(g);
            testfield.paint(g);
            mytest.paint(g);
        }
    }
    
    public void tick() {
        mytest.fall(testfield);
        if (mytest.position[1] > testfield.height) {
            merge(mytest, testfield);
            mytest.position[1] = -1;
        }
    }
    
    public void merge(Tetromino t, Field f) {
        for (int i = 0; i < t.matrix.length; i++) {
            for (int j = 0; j < t.matrix.length; j++) {
                f.field[t.position[0] + i][t.position[1] + j] = t.matrix[i][j];
            }
        }
        System.out.println(f);
    }
    
    
    /**
     * Creates new form tetris
     */
    public Main() {
        initComponents();
        clock.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playfield = new MyPanel();
        titlelabel = new javax.swing.JLabel();
        playbutton = new javax.swing.JButton();
        highscorelabel = new javax.swing.JLabel();
        newgamebutton = new javax.swing.JButton();
        nextlabel = new javax.swing.JLabel();
        piecepreview = new javax.swing.JPanel();
        scorelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 1400));

        playfield.setBackground(new java.awt.Color(0, 0, 0));
        playfield.setPreferredSize(new java.awt.Dimension(600, 1200));

        javax.swing.GroupLayout playfieldLayout = new javax.swing.GroupLayout(playfield);
        playfield.setLayout(playfieldLayout);
        playfieldLayout.setHorizontalGroup(
            playfieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        playfieldLayout.setVerticalGroup(
            playfieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );

        titlelabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        titlelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlelabel.setText("TETRIS");
        titlelabel.setToolTipText("");

        playbutton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playbutton.setText("Play");
        playbutton.setPreferredSize(new java.awt.Dimension(100, 50));

        highscorelabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        highscorelabel.setText("High score: 0");

        newgamebutton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newgamebutton.setText("New Game");
        newgamebutton.setPreferredSize(new java.awt.Dimension(200, 60));

        nextlabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nextlabel.setText("Next: ");

        piecepreview.setBackground(new java.awt.Color(200, 200, 200));
        piecepreview.setPreferredSize(new java.awt.Dimension(240, 240));

        javax.swing.GroupLayout piecepreviewLayout = new javax.swing.GroupLayout(piecepreview);
        piecepreview.setLayout(piecepreviewLayout);
        piecepreviewLayout.setHorizontalGroup(
            piecepreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        piecepreviewLayout.setVerticalGroup(
            piecepreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        scorelabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        scorelabel.setText("Score: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piecepreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scorelabel)
                    .addComponent(highscorelabel)
                    .addComponent(playbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newgamebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titlelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newgamebutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 112, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(playfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(nextlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piecepreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scorelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(highscorelabel)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel highscorelabel;
    private javax.swing.JButton newgamebutton;
    private javax.swing.JLabel nextlabel;
    private javax.swing.JPanel piecepreview;
    private javax.swing.JButton playbutton;
    private javax.swing.JPanel playfield;
    private javax.swing.JLabel scorelabel;
    private javax.swing.JLabel titlelabel;
    // End of variables declaration//GEN-END:variables
}
